### ISSUE TITLE
CT empty container not supported

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gases-intro#10] opened 2021-08-31 15:39 UTC
```
gases-intro : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/phet-io-wrappers/state/?sim=gases-intro&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gases-intro%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1630381649945%22%2C%22timestamp%22%3A1630400086807%7D
Uncaught Error: Uncaught Error: Assertion failed: empty container not supported
Error: Assertion failed: empty container not supported
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/assert/js/assert.js:25:13)
at IdealModel.computeIdealTemperature (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/gas-properties/js/common/model/IdealGasLawModel.js:476:15)
at IdealModel.compensateForHoldConstant (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/gas-properties/js/common/model/IdealGasLawModel.js:408:39)
at IdealModel.updateModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/gas-properties/js/common/model/IdealGasLawModel.js:340:10)
at IdealModel.updateWhenPaused (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/gas-properties/js/common/model/IdealGasLawModel.js:360:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/gas-properties/js/common/model/IdealGasLawModel.js:137:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/axon/js/Multilink.js:47:11)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/axon/js/TinyEmitter.js:86:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/axon/js/Property.js:271:23)
at PhaseCallback.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630381649945/axon/js/Property.js:321:47)
id: Bayes Chrome
Snapshot from 8/30/2021, 9:47:29 PM
```

**Comment by pixelzoom** [comment] 2021-09-03 00:59
gases-intro is a subset of gas-properties, so this is a duplicate of https://github.com/phetsims/gas-properties/issues/196.  Closing as duplicate.

**Closed by pixelzoom** 2021-09-03 00:59 UTC
Labels: type:automated-testing
